export const albums = [
	{
		cover: 'reflections-of-a-lost-teen.jpg',
		webpcover: 'reflections-of-a-lost-teen.webp',
		spotifyUrl: null,
		appleMusicUrl: null,
		year: '2006',
		title: 'Reflections of a Lost Teen',
		copy:
			'This was the album I produced in high school. I sold it out of the trunk of my car. This was before I sang. I only rapped. No one has ever really heard it except my schoolmates.',
	},
	{
		cover: 'a-matter-of-time.jpg',
		webpcover: 'a-matter-of-time.webp',
		spotifyUrl: 'https://open.spotify.com/album/3YqbqVW4Rz8DCPxL2WBCvc',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/a-matter-of-time/1357004981?mt=1&app=music',
		year: '2009',
		title: 'A Matter of Time',
		copy: 'This was the mixtape I made in my dorm room that sort of started my professional career.',
	},
	{
		cover: 'one-foot-out-the-door.jpg',
		webpcover: 'one-foot-out-the-door.webp',
		spotifyUrl: 'https://open.spotify.com/album/0oxxs8JLFwTbbTzSf0wrZI',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/one-foot-out-the-door/1258303649?mt=1&app=music',
		year: '2009',
		title: 'One Foot Out The Door',
		copy: 'This was my second mixtape.',
	},
	{
		cover: '31-minutes-to-takeoff.jpg',
		webpcover: '31-minutes-to-takeoff.webp',
		spotifyUrl: 'https://open.spotify.com/album/2nnIlWcriIqcJtjduWcTRl',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/31-minutes-to-takeoff/383458566?mt=1&app=music',
		year: '2010',
		title: '31 Minutes to Takeoff',
		copy: 'This was my first studio album.',
	},
	{
		cover: 'the-layover.jpg',
		webpcover: 'the-layover.webp',
		spotifyUrl: 'https://open.spotify.com/album/49XLJ6XYJj7j2m1NWchu30',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/the-layover/1305544105?mt=1&app=music',
		year: '2011',
		title: 'The Layover',
		copy: 'This was my really cool mixtape from 2011.',
	},
	{
		cover: 'no-album-cover.svg',
		svg: true,
		spotifyUrl: null,
		appleMusicUrl: null,
		year: '2012',
		title: 'Sky High',
		copy: '(never released)',
	},
	{
		cover: 'pages.jpg',
		webpcover: 'pages.webp',
		spotifyUrl: null,
		appleMusicUrl: null,
		year: '2014',
		title: 'Pages',
		copy: '(never released)',
	},
	{
		cover: 'at-night-alone.jpg',
		webpcover: 'at-night-alone.webp',
		spotifyUrl: 'https://open.spotify.com/album/1Tz3Ai1guEFf4hV3d9i17K',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/at-night-alone/1093895706?mt=1&app=music',
		year: '2016',
		title: 'At Night, Alone.',
		copy:
			'This was the album where I got really good at songwriting. One of the songs “I Took A Pill in Ibiza” got really popular and nominated for a Grammy.',
	},
	{
		cover: 'mansionz.jpg',
		webpcover: 'mansionz.webp',
		spotifyUrl: 'https://open.spotify.com/album/5WS1g0cKtjfK6eDoSLdv7d',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/mansionz/1216939703?mt=1&app=music',
		year: '2017',
		title: 'Mansionz',
		copy: 'This was the album I made with Blackbear. Mansionz is our band that we have together. We dyed our hair green.',
	},
	{
		cover: 'tear-drops-and-balloons.jpg',
		webpcover: 'tear-drops-and-balloons.webp',
		spotifyUrl: 'https://open.spotify.com/album/0Neg41qXHsWHsA6Q7KY44P',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/tear-drops-and-balloons/1353591745?mt=1&app=music',
		year: '2017',
		title: 'Tear Drops and Balloons',
		copy: 'This is the audiobook of my book of poetry, “Tear Drops and Balloons"',
	},
	{
		cover: 'i-was-born-in-detroit-on-a-very-very-very-very-very-very-very-cold-day.jpg',
		webpcover: 'i-was-born-in-detroit-on-a-very-very-very-very-very-very-very-cold-day.webp',
		spotifyUrl: 'https://open.spotify.com/album/6ONK4W1seR3xnhK1SHtkwi',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/i-was-born-in-detroit-on-very-very-very-very-very-very/1337377845?mt=1&app=music',
		year: '2018',
		title: 'i was born in detroit on a very, very, very, very, very, very, very cold day',
		copy:
			'This is a LIVE album that I made as I toured with my band, The Legendary Mike Posner Band. Each night I did a new poem at the concerts. The band had never heard the poems until we were on the stage. They made up the music each night to follow what I was saying. That’s what made them legendary.',
	},
	{
		cover: 'album-cover.svg',
		svg: true,
		webpcover: 'album-cover.webp',
		spotifyUrl: 'https://open.spotify.com/artist/2KsP6tYLJlTBvSUxnwlVWa',
		appleMusicUrl: 'https://geo.itunes.apple.com/us/album/a-real-good-kid/1449093091?mt=1&app=music',
		year: '2018',
		title: 'A Real Good Kid.',
		copy: 'This is the best album ever. Seriously, I really love this album.',
	},
];
